- link:
    ~/.config/polybar/config: polybar/config.linux-workstation
    ~/.config/polybar/launch.sh: polybar/launch.sh
    ~/.config/polybar/scripts:
        path: polybar/scripts
        create: true
    ~/.config/polybar/gmail:
        path: polybar/gmail
        create: true
